version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: taxi24-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build: .
    container_name: taxi24-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/taxi24?authSource=admin
      PORT: 3000
    volumes:
      - .:/usr/src/app
      - taxi24-node-modules:/usr/src/app/node_modules

volumes:
  mongo-data:
  taxi24-node-modules:
